### PR TITLE
resolves #276 try to use KindleGen/EPUBCheck binary from `$PATH`

### LINKED ISSUE #276: Attempt to use KindleGen/epubcheck binary from $PATH
... if everything else fails.

### PR DESCRIPTION
**Pull request by slonopotamus**

### CODE REVIEW

**Comment by mojavelinux** [comment]
You are correct to only do this if the KINDLEGEN env var is not set. That gives the user the ability to avoid the use of the kindlegen on the PATH, which is an important for security, I would think.

File: lib/asciidoctor-epub3/packager.rb [hunk 1]
```diff
@@ -615,24 +615,35 @@ def package options = {}
...
-          argv = [kindlegen_cmd]
-        else
-          begin
-            require 'kindlegen' unless defined? ::Kindlegen
-          rescue LoadError => e
-            raise 'Unable to find KindleGen. Either install the kindlegen gem or set KINDLEGEN environment variable with path to KindleGen executable', cause: e
-          end
-          argv = [::Kindlegen.command.to_s]
+      def get_kindlegen_command
+        unless (result = ENV['KINDLEGEN']).nil?
```
Comment (ysb33r) [inline lib/asciidoctor-epub3/packager.rb]: I would like that besides finding it in the environment there is another way of locating the binary i.e. via an attribute. This allows external downloaders to set the path. For instance in Gradle we are forced to run this out of process i.e. another JVM because of the environmental variable, but if there is a way of setting it, then we can utilise in-process generation.

Comment (slonopotamus) [reply lib/asciidoctor-epub3/packager.rb]: You mean, via document attribute?

Comment (slonopotamus) [reply lib/asciidoctor-epub3/packager.rb]: @mojavelinux could suggest attribute name for this so we don't acidentally clash with other asciidoctor machinery?

Comment (slonopotamus) [reply lib/asciidoctor-epub3/packager.rb]: @ysb33r I think, the order will be:

1. env var
2. attribute
3. kindlegen gem
4. PATH

Comment (slonopotamus) [reply lib/asciidoctor-epub3/packager.rb]: After more thinking, I want to make attribute higher priority than env var. Case: user has env var defined and calls `asciidoctor-epub3 -a ebook-kindlegen-binary-path=/path <book>`. It is clear that their intent to override global behavior for this particular invocation.

Comment (slonopotamus) [reply lib/asciidoctor-epub3/packager.rb]: @mojavelinux are there any security concerns about passing kindlegen path through document attributes? Is there any alternative option to pass settings to `Asciidoctor::Epub3::Packager` that bypass the document itself?

Comment (slonopotamus) [reply lib/asciidoctor-epub3/packager.rb]: @ysb33r I've updated PR with document attributes to specify KindleGen/EPUBCheck executable location, but still waiting for @mojavelinux to review this.
